swagger: '2.0'
info:
  contact: {}
  description: An API for interacting with Google Cloud Storage
  title: FT GCS API
  version: '1.0'
paths:
  /:
    get:
      parameters: []
      responses:
        '200':
          description: ''
      operationId: AppController_getHello
  /storage/download:
    get:
      parameters:
        - in: query
          name: filename
          required: true
          type: string
      responses:
        '200':
          description: ''
      operationId: StorageController_downloadFile
  '/storage/rename/{id}':
    post:
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '201':
          description: ''
      operationId: StorageController_update
  /storage/upload:
    post:
      parameters: []
      responses:
        '201':
          description: ''
      operationId: StorageController_uploadFile
  '/storage/{id}':
    delete:
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: ''
      operationId: StorageController_remove
definitions: {}
tags: []
x-components: {}

x-google-backend:
  address: https://ft-tracks-api-zlauhlisia-uc.a.run.app
