version: 2.1
jobs:
  build-and-generate-api-spec:
    docker:
      - image: thomashodonnell/ts-node-ci
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            yarn
            yarn api-spec:generate
            echo 'x-google-backend:\n  address: $TRACKS_API_URL' >> openApi2Spec.yaml
            cat openApi2Spec.yaml
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud config set project ${GOOGLE_PROJECT_ID}
            gcloud config set compute/zone ${GOOGLE_COMPUTE_ZONE}


workflows:
 Example_Workflow:
   jobs:
     - build-and-generate-api-spec
