version: 2.1
jobs:
  I-Have-Code:
    docker:
      - image: thomashodonnell/ts-node-ci
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            yarn api-spec:generate
            cat openApi2Spec.yaml
  Run-With-Node:
    docker:
      - image: cimg/node:17.2
    steps:
      - run:
          name: Running In A Container With Node
          command: |
            node -v
  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'

workflows:
 Example_Workflow:
   jobs:
     - I-Have-Code
     - Run-With-Node
     - Hold-For-Approval:
         type: approval
         requires:
           - Run-With-Node
           - I-Have-Code
     - Now-Complete:
         requires:
           - Hold-For-Approval