version: 2.1
jobs:
  build-and-generate-api-spec:
    docker:
      - image: thomashodonnell/ts-node-ci
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            yarn
            yarn api-spec:generate 
            echo 'x-google-backend:' >> openApi2Spec.yaml
            echo '  address: $TRACKS_API_URL' >> openApi2Spec.yaml
            cat openApi2Spec.yaml
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud config set project ${GOOGLE_PROJECT_ID}
            gcloud api-gateway api-configs create storage-api-config-${CIRCLE_WORKFLOW_JOB_ID} --api=ft-proxy-api --openapi-spec=openApi2Spec.yaml --project=fresh-traks --backend-auth-service-account=api-gateway-sa@fresh-traks.iam.gserviceaccount.com
            gcloud api-gateway gateways update ft-api-gateway-storage --api=ft-proxy-api --api-config=storage-api-config-${CIRCLE_WORKFLOW_JOB_ID} --location=us-east1 --project=fresh-traks


workflows:
 Example_Workflow:
   jobs:
     - build-and-generate-api-spec
